[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "outdoor pistol miracle gas jelly identify suggest vendor zebra sample buddy lazy smooth author repair axis blood chat genre decrease tobacco skin same network"
